export enum Role {
  USER = "USER",
  MANAGER = "MANAGER",
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum RequestStatus {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAYMENT_SUBMITTED = "PAYMENT_SUBMITTED",
  PAYMENT_VERIFIED = "PAYMENT_VERIFIED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  APPROVED = "APPROVED",
  READY_FOR_DELIVERY = "READY_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
}

export enum PaymentMethod {
  BKASH = "BKASH",
  NAGAD = "NAGAD",
  ROCKET = "ROCKET",
  DUTCH_BANGLA = "DUTCH_BANGLA",
  BANK_TRANSFER = "BANK_TRANSFER",
  CASH = "CASH",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  SUBMITTED = "SUBMITTED",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
  REFUNDED = "REFUNDED",
}

export enum DocumentType {
  USER_UPLOAD = "USER_UPLOAD",
  PAYMENT_PROOF = "PAYMENT_PROOF",
  ADDITIONAL_DOCUMENT = "ADDITIONAL_DOCUMENT",
  FINAL_DELIVERY = "FINAL_DELIVERY",
  INTERNAL_DOCUMENT = "INTERNAL_DOCUMENT",
}

export enum NotificationType {
  REQUEST_SUBMITTED = "REQUEST_SUBMITTED",
  REQUEST_UNDER_REVIEW = "REQUEST_UNDER_REVIEW",
  PAYMENT_REQUIRED = "PAYMENT_REQUIRED",
  PAYMENT_SUBMITTED = "PAYMENT_SUBMITTED",
  PAYMENT_VERIFIED = "PAYMENT_VERIFIED",
  PAYMENT_REJECTED = "PAYMENT_REJECTED",
  REQUEST_IN_PROGRESS = "REQUEST_IN_PROGRESS",
  REQUEST_COMPLETED = "REQUEST_COMPLETED",
  REQUEST_REJECTED = "REQUEST_REJECTED",
  REQUEST_CANCELLED = "REQUEST_CANCELLED",
  DOCUMENT_REQUESTED = "DOCUMENT_REQUESTED",
  ADMIN_ALERT = "ADMIN_ALERT",
  GENERAL = "GENERAL",
}

export enum ActionType {
  REQUEST_CREATED = "REQUEST_CREATED",
  REQUEST_UPDATED = "REQUEST_UPDATED",
  REQUEST_STATUS_CHANGED = "REQUEST_STATUS_CHANGED",
  REQUEST_ASSIGNED = "REQUEST_ASSIGNED",
  REQUEST_NOTE_ADDED = "REQUEST_NOTE_ADDED",
  REQUEST_CANCELLED = "REQUEST_CANCELLED",
  REQUEST_REJECTED = "REQUEST_REJECTED",
  REQUEST_COMPLETED = "REQUEST_COMPLETED",
  REQUEST_QUOTE_SET = "REQUEST_QUOTE_SET",
  REQUEST_DELIVERED = "REQUEST_DELIVERED",

  PAYMENT_SUBMITTED = "PAYMENT_SUBMITTED",
  PAYMENT_VERIFIED = "PAYMENT_VERIFIED",
  PAYMENT_REJECTED = "PAYMENT_REJECTED",
  PAYMENT_REFUNDED = "PAYMENT_REFUNDED",

  DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED",
  DOCUMENT_DELETED = "DOCUMENT_DELETED",

  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_ROLE_CHANGED = "USER_ROLE_CHANGED",
  USER_ACTIVATED = "USER_ACTIVATED",
  USER_DEACTIVATED = "USER_DEACTIVATED",

  SERVICE_CREATED = "SERVICE_CREATED",
  SERVICE_UPDATED = "SERVICE_UPDATED",
  SERVICE_TOGGLED = "SERVICE_TOGGLED",

  USER_LOGIN = "USER_LOGIN",
  USER_LOGOUT = "USER_LOGOUT",
  PASSWORD_RESET = "PASSWORD_RESET",
}

export enum FieldType {
  TEXT = "TEXT",
  TEXTAREA = "TEXTAREA",
  NUMBER = "NUMBER",
  EMAIL = "EMAIL",
  PHONE = "PHONE",
  PASSWORD = "PASSWORD",
  DATE = "DATE",
  FILE = "FILE",
  SELECT = "SELECT",
  MULTI_SELECT = "MULTI_SELECT",
  RADIO = "RADIO",
  CHECKBOX = "CHECKBOX",
  URL = "URL",
}

export enum GuestSource {
  FACEBOOK = "FACEBOOK",
  WHATSAPP = "WHATSAPP",
  LINKEDIN = "LINKEDIN",
  TELEGRAM = "TELEGRAM",
  WEBSITE = "WEBSITE",
  REFERRAL = "REFERRAL",
  OTHERS = "OTHERS",
}